name: class deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        #Run single command using the runners shell 
    - name: Installing node module
      uses: action/setup-node@v2
    
            
    - name: Installing surge 
    - run:  npm-install --global surge
    - run: surge ./ class-20.surge.sh/ --token ${{ secrets.CLASS-20}} 

